# Generated by Django 3.2.2 on 2021-05-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='title',
        ),
    ]
